services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orcamento
      - POSTGRES_USER=orcamento
      - POSTGRES_PASSWORD=orcamento
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orcamento"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      args:
        UV_NO_DEV: true
    # volumes: # - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env-compose
    # environment:
    #   - ENVIRONMENT=development
    #   - DEBUG=True
    #   - SECRET_KEY=dev-secret-key-change-me
    #   - ALLOWED_HOSTS=*
    #   - DATABASE_URL=postgres://orcamento:orcamento@db:5432/orcamento
    depends_on:
      db:
        condition: service_healthy
    command: production
volumes:
  postgres_data:
