services:
  db:
    image: postgres:16
    container_name: orcamento-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orcamento
      - POSTGRES_USER=orcamento
      - POSTGRES_PASSWORD=orcamento
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orcamento"]
      interval: 2s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      args:
        UV_NO_DEV: true
    ports:
      - "8000:8000"
    env_file:
      - .env-compose
    depends_on:
      db:
        condition: service_healthy
    command: production
volumes:
  postgres_data:
